### ISSUE TITLE
new layout

### ISSUE THREAD

**Issue by TheShooter89** [TheShooter89/rst-sylvester#16]
migrate to new layout

🎯️ more polished and consistent layout
🎯️ coherent look on mobile

💡️ great inspiration source is [this bulma template gallery](https://bulmatemplates.github.io/bulma-templates/)

---

related issues, along with inspirations references:

- [x] 📣️ #19  styles: add custom theme and styles

- [x] ✒️ #13 font: Big Shoulders - source on [Google Fonts](https://fonts.google.com/specimen/Big+Shoulders+Display)

- [ ] 🔁️ #24 body (base layout): move body to its own template

- [x] 🔥️ #17 navbar: App Page template ([demo](https://bulmatemplates.github.io/bulma-templates/templates/app-page.html) - [source](https://github.com/BulmaTemplates/bulma-templates/blob/master/templates/app-page.html))

- [ ] 🔥️ #11  body: Contact Us template ([demo](https://bulmatemplates.github.io/bulma-templates/templates/contact.html) - [source](https://github.com/BulmaTemplates/bulma-templates/blob/master/templates/contact.html))

- [ ] 🔥️ #18  login form: Register template ([demo](https://bulmatemplates.github.io/bulma-templates/templates/register.html) - [source](https://github.com/BulmaTemplates/bulma-templates/blob/master/templates/register.html))
